### ISSUE TITLE
Error on `start()`: "LAxis not defined"

### ISSUE THREAD

**Issue by claybridges** [albheim/PoleExploration#1]
Looks like this:

<img width="623" alt="Screen Shot 2021-04-04 at 6 01 44 PM" src="https://user-images.githubusercontent.com/96004/113522614-0c4a3e00-9570-11eb-97bd-8a1eafdf9aae.png">

Text:
```
ERROR: UndefVarError: LAxis not defined
Stacktrace:
 [1] scenesetup()
   @ PoleExploration ~/.julia/packages/PoleExploration/dMJJq/src/PoleExploration.jl:38
 [2] start()
   @ PoleExploration ~/.julia/packages/PoleExploration/dMJJq/src/PoleExploration.jl:193
 [3] top-level scope
   @ REPL[4]:1
```

**Comment by albheim** [comment]
Thanks for notifying!

They were working on the Makie GUI stuff when I was building this so it seems like some stuff has changed in the newer version. Will take a look at it when I get the time, but in the meantime you could instead clone the git repo (or dev it), and start julia with `julia --project /path/to/repo/PoleExploration.jl/` and run
```julia
julia> ]
pkg> instantiate
julia> using PoleExploration
julia> start()
```

This should make sure you use the same versions of dependencies as are defined in the Manifest.toml in the repo, and thus should allow you to run it.
